export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "Wandr Phase 1 API",
    version: "1.0.0",
    description: "Production-grade Phase 1 travel platform API for auth, profiles, destinations, hotels, activities, wishlist, reviews, uploads and global search.",
  },
  servers: [{ url: "/api/v1" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
    },
  },
  paths: {
    "/auth/register": { post: { tags: ["Auth"], summary: "Register user" } },
    "/auth/login": { post: { tags: ["Auth"], summary: "Login user" } },
    "/auth/logout": { post: { tags: ["Auth"], summary: "Revoke refresh token" } },
    "/auth/refresh": { post: { tags: ["Auth"], summary: "Rotate refresh token and issue access token" } },
    "/auth/forgot-password": { post: { tags: ["Auth"], summary: "Create password reset token" } },
    "/auth/reset-password": { post: { tags: ["Auth"], summary: "Reset password" } },
    "/auth/send-verification": { post: { tags: ["Auth"], summary: "Create email verification token" } },
    "/auth/verify-email": { post: { tags: ["Auth"], summary: "Verify email address" } },
    "/profile": {
      get: { tags: ["Profile"], summary: "Get profile" },
      patch: { tags: ["Profile"], summary: "Update profile" },
    },
    "/profile/avatar": { post: { tags: ["Profile"], summary: "Upload avatar to Cloudinary" } },
    "/destinations": {
      get: { tags: ["Destinations"], summary: "List destinations with search, filters and pagination" },
      post: { tags: ["Destinations"], summary: "Create destination" },
    },
    "/destinations/{slug}": { get: { tags: ["Destinations"], summary: "Destination details with nearby destinations, activities, hotels and weather" } },
    "/destinations/{id}": {
      patch: { tags: ["Destinations"], summary: "Update destination" },
      delete: { tags: ["Destinations"], summary: "Delete destination" },
    },
    "/hotels": {
      get: { tags: ["Hotels"], summary: "List hotels with search, filters and pagination" },
      post: { tags: ["Hotels"], summary: "Create hotel" },
    },
    "/activities": {
      get: { tags: ["Activities"], summary: "List activities with search and filters" },
      post: { tags: ["Activities"], summary: "Create activity" },
    },
    "/wishlist": {
      get: { tags: ["Wishlist"], summary: "Get user wishlist" },
      post: { tags: ["Wishlist"], summary: "Add destination to wishlist" },
    },
    "/reviews": {
      get: { tags: ["Reviews"], summary: "List destination reviews" },
      post: { tags: ["Reviews"], summary: "Create review and recalculate destination rating" },
    },
    "/search": { get: { tags: ["Search"], summary: "Search destinations, hotels and activities" } },
    "/packages": {
      get: { tags: ["Packages"], summary: "Search packages" },
      post: { tags: ["Packages"], summary: "Create package" },
    },
    "/packages/featured": { get: { tags: ["Packages"], summary: "Featured packages" } },
    "/packages/trending": { get: { tags: ["Packages"], summary: "Trending packages" } },
    "/packages/{slug}": { get: { tags: ["Packages"], summary: "Get package with itinerary" } },
    "/itineraries": { post: { tags: ["Itinerary"], summary: "Attach day-wise itinerary to package" } },
    "/bookings": { post: { tags: ["Bookings"], summary: "Create booking with inventory lock" } },
    "/bookings/history": { get: { tags: ["Bookings"], summary: "User booking history" } },
    "/bookings/{id}/cancel": { post: { tags: ["Bookings"], summary: "Cancel booking and release inventory" } },
    "/inventory/availability": { get: { tags: ["Inventory"], summary: "Package and hotel availability" } },
    "/inventory": { put: { tags: ["Inventory"], summary: "Upsert package or hotel inventory" } },
    "/payments/create-order": { post: { tags: ["Payments"], summary: "Create Stripe PaymentIntent" } },
    "/payments/verify": { post: { tags: ["Payments"], summary: "Verify Stripe payment" } },
    "/payments/refund": { post: { tags: ["Payments"], summary: "Refund Stripe payment" } },
    "/payments/history": { get: { tags: ["Payments"], summary: "User payment history" } },
    "/weather/{destination}": { get: { tags: ["Weather"], summary: "Weather with Redis cache" } },
    "/planner/generate": { post: { tags: ["AI Planner"], summary: "Generate AI trip plan" } },
    "/notifications": { get: { tags: ["Notifications"], summary: "In-app notifications" } },
    "/blogs": {
      get: { tags: ["Blogs"], summary: "Search blogs" },
      post: { tags: ["Blogs"], summary: "Create blog" },
    },
    "/blogs/{slug}": { get: { tags: ["Blogs"], summary: "Get blog" } },
    "/analytics/dashboard": { get: { tags: ["Analytics"], summary: "Admin dashboard analytics" } },
    "/analytics/revenue": { get: { tags: ["Analytics"], summary: "Monthly revenue" } },
    "/analytics/bookings": { get: { tags: ["Analytics"], summary: "Booking growth" } },
    "/analytics/users": { get: { tags: ["Analytics"], summary: "User growth" } },
    "/admin/dashboard": { get: { tags: ["Admin"], summary: "Enterprise admin dashboard" } },
    "/admin/users": { get: { tags: ["Admin"], summary: "Admin users list" } },
    "/chat": { post: { tags: ["AI Assistant"], summary: "AI travel chatbot with memory" } },
    "/recommendations": { get: { tags: ["Recommendations"], summary: "Personalized recommendations" } },
    "/recommendations/packages": { get: { tags: ["Recommendations"], summary: "Recommended packages" } },
    "/recommendations/destinations": { get: { tags: ["Recommendations"], summary: "Recommended destinations" } },
    "/recently-viewed": { post: { tags: ["Recently Viewed"], summary: "Track viewed entity" } },
    "/search/advanced": { get: { tags: ["Advanced Search"], summary: "Fuzzy filtered global search" } },
    "/search/suggestions": { get: { tags: ["Advanced Search"], summary: "Autocomplete and suggestions" } },
    "/search/trending": { get: { tags: ["Advanced Search"], summary: "Trending searches" } },
    "/support/tickets": { get: { tags: ["Support"], summary: "List tickets" }, post: { tags: ["Support"], summary: "Create ticket" } },
    "/coupons": { get: { tags: ["Coupons"], summary: "Manage coupons" }, post: { tags: ["Coupons"], summary: "Create coupon" } },
    "/coupons/apply": { post: { tags: ["Coupons"], summary: "Apply coupon" } },
    "/referrals/code": { get: { tags: ["Referrals"], summary: "Get referral code" } },
    "/loyalty": { get: { tags: ["Loyalty"], summary: "Reward account and history" } },
    "/seo/meta": { get: { tags: ["SEO"], summary: "Get meta tags" }, put: { tags: ["SEO"], summary: "Upsert meta tags" } },
    "/seo/sitemap": { get: { tags: ["SEO"], summary: "Dynamic sitemap" } },
    "/audit-logs": { get: { tags: ["Audit"], summary: "Audit log search" } },
    "/files/upload": { post: { tags: ["Files"], summary: "Cloudinary bulk upload" } },
    "/feature-flags": { get: { tags: ["Feature Flags"], summary: "List feature flags" }, put: { tags: ["Feature Flags"], summary: "Upsert feature flag" } },
    "/push/subscribe": { post: { tags: ["Push"], summary: "Register push subscription" } },
    "/email/templates/send": { post: { tags: ["Email"], summary: "Send responsive template email" } },
    "/backups": { get: { tags: ["Backups"], summary: "List backup jobs" }, post: { tags: ["Backups"], summary: "Queue backup job" } },
    "/monitoring": { get: { tags: ["Monitoring"], summary: "Runtime observability snapshot" } },
    "/flights/search": { get: { tags: ["Flights"], summary: "Search flights via provider adapter" } },
    "/flights/details": { get: { tags: ["Flights"], summary: "Flight details" } },
    "/trains/search": { get: { tags: ["Trains"], summary: "Search trains" } },
    "/trains/{id}": { get: { tags: ["Trains"], summary: "Train route and availability" } },
    "/buses/search": { get: { tags: ["Buses"], summary: "Search buses" } },
    "/pricing/quote": { post: { tags: ["Pricing"], summary: "Dynamic price quote" } },
    "/pricing/rules": { put: { tags: ["Pricing"], summary: "Upsert dynamic pricing rule" } },
    "/homepage/personalized": { get: { tags: ["Homepage"], summary: "Personalized homepage" } },
    "/booking-queue": { post: { tags: ["Booking Queue"], summary: "Queue booking for real-time engine" } },
    "/cache/warm": { post: { tags: ["Cache"], summary: "Warm Redis caches" } },
    "/cache/{group}": { delete: { tags: ["Cache"], summary: "Invalidate cache group" } },
    "/search/optimized": { get: { tags: ["Search"], summary: "Optimized ranked search" } },
    "/metrics/api": { get: { tags: ["Monitoring"], summary: "API metrics" } },
    "/performance/audit": { post: { tags: ["Performance"], summary: "Run performance audit snapshot" } },
    "/images/optimize": { get: { tags: ["Images"], summary: "Cloudinary optimized variants" } },
    "/business-insights": { get: { tags: ["Business Intelligence"], summary: "Revenue and conversion insights" } },
    "/errors/capture": { post: { tags: ["Errors"], summary: "Capture tracked error" } },
  },
};
